# Generated by Django 2.2.1 on 2019-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190519_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='img/blog-1.jpg', upload_to='blog/'),
        ),
    ]
